"""Curated default source catalog bundled with the application."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class CuratedSource:
    name: str
    url: str
    category: str
    source_type: str
    language: str
    region: str
    fetch_interval_minutes: int = 30
    trust_level: int = 4


CURATED_SOURCES: list[CuratedSource] = [
    # 国内时政
    CuratedSource(
        "人民日报",
        "http://www.people.com.cn/rss/politics.xml",
        "国内时政",
        "rss",
        "zh-CN",
        "CN",
        60,
    ),
    CuratedSource(
        "凤凰网",
        "https://rsshub.ddns.net/ifeng/news",
        "国内时政",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "观察者网",
        "https://rsshub.ddns.net/guancha",
        "国内时政",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "观察者热点",
        "https://rsshub.ddns.net/guancha/redian",
        "国内时政",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "网易今日关注",
        "https://rsshub.ddns.net/163/today",
        "国内综合",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    # 国内财经
    CuratedSource(
        "财新最新",
        "https://rsshub.ddns.net/caixin/latest",
        "国内财经",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "第一财经",
        "https://rsshub.ddns.net/yicai/news",
        "国内财经",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "华尔街见闻 - 中国",
        "https://rsshub.ddns.net/wallstreetcn/news/china",
        "国内财经",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "华尔街见闻 - 全球",
        "https://rsshub.ddns.net/wallstreetcn/news/global",
        "国际财经",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    # 国内科技 / AI
    CuratedSource(
        "36氪快讯",
        "https://rsshub.ddns.net/36kr/newsflashes",
        "国内科技",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "36氪资讯",
        "https://rsshub.ddns.net/36kr/information/web_news",
        "国内科技",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "虎嗅",
        "https://rsshub.ddns.net/huxiu/article",
        "国内科技",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "少数派",
        "https://rsshub.ddns.net/sspai/index",
        "国内科技",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "少数派 Matrix",
        "https://rsshub.ddns.net/sspai/matrix",
        "国内科技",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "掘金周榜",
        "https://rsshub.ddns.net/juejin/trending/all/weekly",
        "国内科技",
        "rsshub",
        "zh-CN",
        "CN",
        60,
    ),
    CuratedSource(
        "IT之家 24h",
        "https://rsshub.ddns.net/ithome/ranking/24h",
        "国内科技",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "雷峰网",
        "https://rsshub.ddns.net/leiphone",
        "国内AI",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "Solidot",
        "https://rsshub.ddns.net/solidot/www",
        "国内科技",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    # 国内综合
    CuratedSource(
        "知乎热榜",
        "https://rsshub.ddns.net/zhihu/hot",
        "国内综合",
        "rsshub",
        "zh-CN",
        "CN",
        15,
    ),
    # 国际综合
    CuratedSource(
        "BBC 中文",
        "https://rsshub.ddns.net/bbc/chinese",
        "国际综合",
        "rsshub",
        "zh-CN",
        "UK",
        30,
    ),
    CuratedSource(
        "AP Top News",
        "https://rsshub.ddns.net/apnews/topics/ap-top-news",
        "国际综合",
        "rsshub",
        "en",
        "US",
        30,
    ),
    CuratedSource(
        "NPR News",
        "https://feeds.npr.org/1001/rss.xml",
        "国际综合",
        "rss",
        "en",
        "US",
        30,
    ),
    # 国际科技
    CuratedSource(
        "TechCrunch",
        "https://techcrunch.com/feed/",
        "国际科技",
        "rss",
        "en",
        "US",
        30,
    ),
    CuratedSource(
        "The Verge",
        "https://www.theverge.com/rss/index.xml",
        "国际科技",
        "rss",
        "en",
        "US",
        30,
    ),
    CuratedSource(
        "Ars Technica",
        "https://arstechnica.com/feed/",
        "国际科技",
        "rss",
        "en",
        "US",
        30,
    ),
    CuratedSource(
        "Wired",
        "https://www.wired.com/feed/rss",
        "国际科技",
        "rss",
        "en",
        "US",
        60,
    ),
    CuratedSource(
        "MIT Technology Review",
        "https://www.technologyreview.com/feed/",
        "国际科技",
        "rss",
        "en",
        "US",
        60,
    ),
    CuratedSource(
        "Engadget",
        "https://www.engadget.com/rss.xml",
        "国际科技",
        "rss",
        "en",
        "US",
        30,
    ),
    CuratedSource(
        "CNET",
        "https://www.cnet.com/rss/news/",
        "国际科技",
        "rss",
        "en",
        "US",
        30,
    ),
    CuratedSource(
        "VentureBeat",
        "https://venturebeat.com/feed/",
        "国际科技",
        "rss",
        "en",
        "US",
        30,
    ),
    CuratedSource(
        "Hacker News",
        "https://rsshub.ddns.net/hackernews",
        "国际科技",
        "rsshub",
        "en",
        "US",
        15,
    ),
    CuratedSource(
        "Google AI Blog",
        "https://blog.google/technology/ai/rss/",
        "国际AI",
        "rss",
        "en",
        "US",
        60,
    ),
    # 游戏
    CuratedSource(
        "IGN",
        "https://www.ign.com/rss/articles/feed",
        "游戏",
        "rss",
        "en",
        "US",
        30,
    ),
    CuratedSource(
        "GameSpot",
        "https://www.gamespot.com/feeds/news/",
        "游戏",
        "rss",
        "en",
        "US",
        30,
    ),
    CuratedSource(
        "Eurogamer",
        "https://www.eurogamer.net/?format=rss",
        "游戏",
        "rss",
        "en",
        "UK",
        30,
    ),
    CuratedSource(
        "PC Gamer",
        "https://www.pcgamer.com/rss/",
        "游戏",
        "rss",
        "en",
        "US",
        30,
    ),
    # 科学
    CuratedSource(
        "Nature News",
        "https://www.nature.com/nature.rss",
        "科学",
        "rss",
        "en",
        "UK",
        60,
    ),
    # 视频/文化
    CuratedSource(
        "Bilibili 热门",
        "https://rsshub.ddns.net/bilibili/popular/all",
        "视频/文化",
        "rsshub",
        "zh-CN",
        "CN",
        30,
    ),
    CuratedSource(
        "豆瓣即将上映",
        "https://rsshub.ddns.net/douban/movie/later",
        "视频/文化",
        "rsshub",
        "zh-CN",
        "CN",
        60,
    ),
]

